name: HideCommands
version: '${project.version}'
main: me.luucka.hidecommands.HideCommandsPlugin
api-version: 1.19
authors: [ LuuckA ]
description: Hide commands
libraries:
  - org.spongepowered:configurate-yaml:${libs.configurate-yaml}